# libzmq

ExternalProject_Add(zmq-project
	GIT_REPOSITORY https://github.com/zeromq/libzmq
	UPDATE_COMMAND ""
	INSTALL_COMMAND make install
	LIST_SEPARATOR |
	CMAKE_ARGS 
		-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} 
		-DZMQ_BUILD_TESTS:BOOL=OFF 
		-DBUILD_TESTS:BOOL=OFF 
		-DBUILD_STATIC:BOOL=ON
		-DCMAKE_BUILD_TYPE=Debug
	)

file(MAKE_DIRECTORY ${CMAKE_INSTALL_PREFIX}/include)

add_library(zmq SHARED IMPORTED)
set_property(TARGET zmq 
	PROPERTY IMPORTED_LOCATION 
	${CMAKE_INSTALL_PREFIX}/lib64/${CMAKE_SHARED_LIBRARY_PREFIX}zmq${CMAKE_SHARED_LIBRARY_SUFFIX}
	)
set_property(TARGET zmq 
	PROPERTY INTERFACE_INCLUDE_DIRECTORIES 
	${CMAKE_INSTALL_PREFIX}/include
	)
add_dependencies(zmq zmq-project)
